baseURL = "http://example.org/"
languageCode = "ru-ru"
title = "Высокодоступные MySQL сервера"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
